@API_HostAddress = https://localhost:7241

### Create User
POST {{API_HostAddress}}/api/users
Content-Type: application/json
{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@novastarter.kit",
  "password": "password",
  "role": "Admin"
}

### Get User by ID
GET {{API_HostAddress}}/api/users/6afd5e9f-2b65-4e03-9d33-d2606b884c50
Accept: application/json

### Login User
POST {{API_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "email": "john.doe@novastarter.kit",
  "password": "password"
}